### ISSUE TITLE
Long topics can crash the bot

### ISSUE THREAD

**Issue by mhsdef** [Automattic/breakingbot#77]
```
.start this is a test of a topic way too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long too long
```

```
2024-07-18T18:17:09.287112+00:00 app[web.1]: Error.captureStackTrace(err)
2024-07-18T18:17:09.287112+00:00 app[web.1]: ^
2024-07-18T18:17:09.287113+00:00 app[web.1]:
2024-07-18T18:17:09.287113+00:00 app[web.1]: error: value too long for type character varying(512)
2024-07-18T18:17:09.287113+00:00 app[web.1]: at /app/node_modules/pg/lib/client.js:526:17
2024-07-18T18:17:09.287114+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-18T18:17:09.287114+00:00 app[web.1]: at async file:///app/node_modules/drizzle-orm/node-postgres/session.js:47:22
2024-07-18T18:17:09.287114+00:00 app[web.1]: at async file:///app/dist/lib/boundary/hubot/handlers/incident.js:13:34
2024-07-18T18:17:09.287123+00:00 app[web.1]: at async NodePgSession.transaction (file:///app/node_modules/drizzle-orm/node-postgres/session.js:106:22)
2024-07-18T18:17:09.287124+00:00 app[web.1]: at async incidentStart (file:///app/dist/lib/boundary/hubot/handlers/incident.js:11:20) {
2024-07-18T18:17:09.287124+00:00 app[web.1]: length: 99,
2024-07-18T18:17:09.287124+00:00 app[web.1]: severity: 'ERROR',
2024-07-18T18:17:09.287124+00:00 app[web.1]: code: '22001',
2024-07-18T18:17:09.287125+00:00 app[web.1]: detail: undefined,
2024-07-18T18:17:09.287125+00:00 app[web.1]: hint: undefined,
2024-07-18T18:17:09.287125+00:00 app[web.1]: position: undefined,
2024-07-18T18:17:09.287125+00:00 app[web.1]: internalPosition: undefined,
2024-07-18T18:17:09.287125+00:00 app[web.1]: internalQuery: undefined,
2024-07-18T18:17:09.287125+00:00 app[web.1]: where: undefined,
2024-07-18T18:17:09.287126+00:00 app[web.1]: schema: undefined,
2024-07-18T18:17:09.287126+00:00 app[web.1]: table: undefined,
2024-07-18T18:17:09.287126+00:00 app[web.1]: column: undefined,
2024-07-18T18:17:09.287126+00:00 app[web.1]: dataType: undefined,
2024-07-18T18:17:09.287127+00:00 app[web.1]: constraint: undefined,
2024-07-18T18:17:09.287127+00:00 app[web.1]: file: 'varchar.c',
2024-07-18T18:17:09.287127+00:00 app[web.1]: line: '632',
2024-07-18T18:17:09.287127+00:00 app[web.1]: routine: 'varchar'
2024-07-18T18:17:09.287127+00:00 app[web.1]: }
2024-07-18T18:17:09.287127+00:00 app[web.1]:
2024-07-18T18:17:09.287127+00:00 app[web.1]: Node.js v22.4.1
2024-07-18T18:17:09.298664+00:00 app[web.1]: npm notice
2024-07-18T18:17:09.298665+00:00 app[web.1]: npm notice New patch version of npm available! 10.8.1 -> 10.8.2
2024-07-18T18:17:09.298666+00:00 app[web.1]: npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
2024-07-18T18:17:09.298666+00:00 app[web.1]: npm notice To update run: npm install -g npm@10.8.2
2024-07-18T18:17:09.298666+00:00 app[web.1]: npm notice
2024-07-18T18:17:09.345648+00:00 heroku[web.1]: Process exited with status 1
2024-07-18T18:17:09.371711+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by mhsdef** [comment]
surprising, because the slack 250 char limit is known and we have truncating logic for it

db limit for title is 512

both avenues worth looking over again
